## Author: Bryce Miller - brycezmiller@nnu.edu
## Last Updated by: Bryce Miller

## Import Generic Modules
import os, sys
from datetime import datetime

## Set working directory
os.chdir(os.path.dirname(__file__))

## Add the resource modules path
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "ResourceModules"))

try: ## Irregular try clause, do not comment out in testing
    from Local_Setup import LocalSetup
    from Error_Email import errorEmail
except ImportError:
    from ResourceModules.Local_Setup import LocalSetup
    from ResourceModules.Error_Email import errorEmail

## Define the script name, purpose, and external requirements for logging and error reporting purposes
scriptName = "Combine_Scripts"

scriptPurpose = r"""
This script combines all .py files within the Scripts_TLC directory and its subfolders into a single
.py file that can be uploaded as part of a Claude project for context. The Scripts_TLC\Configs
directory and this script itself are excluded from the output.
"""

externalRequirements = r"""
To function properly this script requires no external dependencies beyond the Python standard library.
It must be located within Scripts_TLC\ActionModules to correctly resolve the Scripts_TLC root directory.
"""

## Initialize LocalSetup and error handler
localSetup = LocalSetup(datetime.now(), __file__)
errorHandler = errorEmail(scriptName, scriptPurpose, externalRequirements, localSetup)

## Define the root Scripts_TLC directory relative to this file's location in ActionModules
scriptsTlcRootPath = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

## Define the directories to ignore during the file walk
ignoredDirectoryPaths = {os.path.join(scriptsTlcRootPath, "Configs")}

## Define the output file path at the Scripts_TLC root level
outputFilePath = os.path.join(scriptsTlcRootPath, "combined_scripts.py")


## This function returns True if the given path lives inside an ignored directory
def isIgnoredPath (p1_path: str) -> bool:
    functionName = "isIgnoredPath"

    ## Get the absolute path of the given path
    absolutePath = os.path.abspath(p1_path)

    ## For each ignored directory path
    for ignoredDirectoryPath in ignoredDirectoryPaths:

        ## If the absolute path starts with the ignored directory path
        if absolutePath.startswith(ignoredDirectoryPath + os.sep) or absolutePath == ignoredDirectoryPath:

            ## Return True
            return True

    ## Return False if no ignored directory path matched
    return False


## This function walks the Scripts_TLC root and returns a sorted list of .py file paths
## excluding ignored directories, the output file, and this script itself
def collectPyFiles (p1_rootPath: str) -> list:
    functionName = "collectPyFiles"

    try:

        ## Define a list to hold the collected .py file paths
        collectedPyFiles = []

        ## Walk the root path
        for dirPath, dirNames, fileNames in os.walk(p1_rootPath):

            ## Prune ignored directories so os.walk won't descend into them
            dirNames[:] = [
                dirName for dirName in dirNames
                if not isIgnoredPath(os.path.join(dirPath, dirName))
            ]

            ## For each file name in sorted order
            for fileName in sorted(fileNames):

                ## If the file is not a .py file, skip it
                if not fileName.endswith(".py"):
                    continue

                ## Get the absolute path of the file
                absoluteFilePath = os.path.abspath(os.path.join(dirPath, fileName))

                ## If the file is this script or the output file, skip it
                if absoluteFilePath in (os.path.abspath(__file__), os.path.abspath(outputFilePath)):
                    continue

                ## Add the file path to the collected .py files list
                collectedPyFiles.append(absoluteFilePath)

        ## Return the sorted list of collected .py file paths
        return sorted(collectedPyFiles)

    except Exception as Error:
        errorHandler.sendError(functionName, Error)


## This function writes all collected .py files into a single combined output file
def combineFiles (p1_pyFiles: list, p1_outputPath: str) -> None:
    functionName = "combineFiles"

    try:

        ## Open the output file for writing
        with open(p1_outputPath, "w", encoding="utf-8") as outputFile:

            ## Write the output file header
            outputFile.write("## =============================================================================\n")
            outputFile.write("## COMBINED SCRIPTS - auto-generated by combine_scripts.py\n")
            outputFile.write(f"## Files included: {len(p1_pyFiles)}\n")
            outputFile.write("## =============================================================================\n\n")

            ## For each collected .py file path
            for pyFilePath in p1_pyFiles:

                ## Get the relative path of the file from the Scripts_TLC root
                relativeFilePath = os.path.relpath(pyFilePath, scriptsTlcRootPath)

                ## Write the file separator and relative path header
                outputFile.write("\n\n")
                outputFile.write("## " + "=" * 75 + "\n")
                outputFile.write(f"## FILE: {relativeFilePath}\n")
                outputFile.write("## " + "=" * 75 + "\n\n")

                ## Open the file and write its contents to the output file
                with open(pyFilePath, "r", encoding="utf-8") as inputFile:
                    outputFile.write(inputFile.read())

        ## Log the result
        localSetup.logger.info(f"Combined {len(p1_pyFiles)} file(s) into {p1_outputPath}")
        print(f"Combined {len(p1_pyFiles)} file(s) into {p1_outputPath}")

    except Exception as Error:
        errorHandler.sendError(functionName, Error)


## This function collects all relevant .py files and combines them into the output file
def combinePyFilesInScriptsTlc () -> None:
    functionName = "combinePyFilesInScriptsTlc"

    try:

        ## Collect all relevant .py files from the Scripts_TLC root
        pyFiles = collectPyFiles(scriptsTlcRootPath)

        ## If no .py files were found
        if not pyFiles:

            ## Log the result and return
            localSetup.logger.warning("No .py files found - nothing to combine.")
            print("No .py files found - nothing to combine.")
            return

        ## Log the files that will be combined
        localSetup.logger.info(f"\nFound {len(pyFiles)} file(s):")
        print(f"Found {len(pyFiles)} file(s):")
        for pyFilePath in pyFiles:
            relPath = os.path.relpath(pyFilePath, scriptsTlcRootPath)
            localSetup.logger.info(f"  {relPath}")
            print(f"  {relPath}")

        ## Combine the collected .py files into the output file
        combineFiles(pyFiles, outputFilePath)

    except Exception as Error:
        errorHandler.sendError(functionName, Error)


if __name__ == "__main__":

    ## Set working directory
    os.chdir(os.path.dirname(__file__))

    ## Combine all .py files in Scripts_TLC into a single output file
    combinePyFilesInScriptsTlc()

    input("Press enter to exit")